### ISSUE TITLE
Load Image

### ISSUE THREAD

**Issue by bacchantes** [sebinsphilip/AppliedRoboticsStudentInterface#1]
This function can be used to replace the simulator camera and test the developed pipeline on a set of custom image

**Comment by sebinsphilip** [comment]
Implemented in commit: Added load and genericImageListener for student Interface

[https://github.com/sebinsphilip/AppliedRoboticsStudentInterface/commit/8f29e5860c170cf49f16dd3804da40840d2729a7](url)
